/* Test that all the different types of epilogue code generated by GCC generate
   valid CFA information by clobbering some callee-saved regs R4:R10.  This will
   cause GCC to generate additional code in the prologue/epilogue which modifies
   the stack.
   If we run through this code with a software watchpoint set, the CFA must be
   valid at every state otherwise GDB will complain.  */

volatile int global_x = 42;

void recurser_1 (int x)
{
  int local_x = 0;

  /* For -mcpu=msp430x this will generate "{PUSHM,POPM} #2, R6".
     For -mcpu=msp430 this will generate individual PUSH/POP insns.  */
  __asm__ ("" : : : "r5");
  __asm__ ("" : : : "r6");

  if (x > 0)
    recurser_1 (x-1);
  local_x = x;
  global_x += x;
  return;
}

void recurser_2 (int x)
{
  int local_x = 0;

  /* For -mcpu=msp430x this will generate "{PUSHM,POPM} #3, R10".
     For -mcpu=msp430 this will generate __mspabi_func_epilog_3.  */
  __asm__ ("" : : : "r8");
  __asm__ ("" : : : "r9");
  __asm__ ("" : : : "r10");

  if (x > 0)
    recurser_2 (x-1);
  local_x = x;
  global_x += x;
  return;
}

int main ()
{
  recurser_1 (2);
  recurser_2 (3);

  return 0;
}
